# Keep in sync with setup.cfg in the root of the project
ignore:
  - "src/manage.py"
  - "src/openforms/wsgi.py"
  - "src/openforms/conf/local_example.py"
  - "**/migrations/*"
  - "*.py-tpl"
  - "**/tests/*"
  - "src/openforms/submissions/management/commands/test_submission_completion.py"
  - "src/openforms/submissions/management/commands/render_confirmation_pdf.py"
  - "src/openforms/formio/management/commands/formio_makemessages.py"
  - "src/openforms/appointments/management/commands/appointment.py"
  - "src/openforms/registrations/management/commands/register_submission.py"
  - "src/openforms/registrations/contrib/microsoft_graph/management/commands/msgraph_list_files.py"
  - "src/openforms/utils/management/commands/check_admin_index.py"
  - "src/openforms/registrations/contrib/stuf_zds/management/commands/stuf_zds_test_stp.py"
  - "src/openforms/plugins/management/commands/disable_demo_plugins.py"
  - "src/openforms/payments/management/commands/checkpaymentemaildupes.py"
  - "src/openforms/registrations/contrib/email/views.py"
